SAMPNAME=RenderPage
CLEAN_UP_FILES=RenderPage-out.pdf
OTHER_OBJS = $(SAMPNAME).o mainproc.o 

include ../../dlutils/common.mak

$(SAMPNAME).o: $(SRC)/$(SAMPNAME).cpp

mainproc.o : $(SRC)/mainproc.cpp

